  services:
    redis:
      image: redis:7.2
      container_name: redis
      ports:
        - '6380:6379'
      networks:
        - dataportal_network
      volumes:
        - redis_data:/data
    users_service:
      container_name: users
      image: postgres:latest
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: User
      ports:
        - '5450:5432'
      volumes:
        - UserData:/var/lib/postgresql/data
      networks:
        - dataportal_network

  volumes:
    UserData: {}
    redis_data: {}

  networks:
    dataportal_network:
      driver: bridge