#spring:
#  application:
#    name: dataportal
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 299404978537-ku2t3638em58j73nd1c863t83ko8qipv.apps.googleusercontent.com
#            client-secret: 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
#            scope: profile, email
#
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: benovsebektas@gmail.com
#    password: klmp yxwd jtdz ptmn
#    properties:
#      mail:
#        transport:
#          protocol: smtp
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#        debug: true
#  datasource:
#    first:
#      url: jdbc:postgresql://localhost:5450/User
#      username: root
#      password: root
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
##  data:
##    redis:
##      host: localhost
##      port: 6380
##      password: redispass  # Buraya Docker Compose'daki şifreyi gir
##
#
#
#
#cloudinary:
#  cloud:
#    name: dddwkgrcy
#  api:
#    key: 668583881613156
#    secret: 7jymaVAgMxu5Pc50toz0YvwJ2ro

spring:
  application:
    name: dataportal
  mail:
    host: smtp.gmail.com
    port: 587
    username: benovsebektas@gmail.com
    password: zcffaibgknbgjvmt  # App Password istifadə edin, boşluqsuz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
        debug: true
  datasource:
    first:
      url: jdbc:postgresql://localhost:5450/User
      username: root
      password: root
    second:
        url: jdbc:postgresql://localhost:5451/Company
        username: root
        password: root
  jpa:
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: localhost
      port: 6379
      password: redispass

cloudinary:
  cloud:
    name: dddwkgrcy
  api:
    key: 668583881613156
    secret: 7jymaVAgMxu5Pc50toz0YvwJ2ro
