spring:
  application:
    base-url: "http://localhost:8080"
    bot-url: "http://127.0.0.1:5000"
    name: dataportal
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 407408718192.apps.googleusercontent.com
            client-secret: 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
            scope: openid email profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"  # Burada `{baseUrl}` uygulamanın temel URL'si olacak
  provider:
    google:
      authorization-uri: https://accounts.google.com/o/oauth2/auth
      token-uri: https://oauth2.googleapis.com/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  mail:
    host: smtp.gmail.com
    port: 587
    username: serxan.babayev.06@gmail.com
    password: klmp yxwd jtdz ptmn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
        debug: true
  datasource:
    first:
      url: jdbc:postgresql://localhost:5450/User
      username: root
      password: root
    second:
      url: jdbc:postgresql://localhost:5451/Page
      username: root
      password: root
    third:
      url: jdbc:postgresql://localhost:5453/DataSet
      username: root
      password: root
    fourth:
      url: jdbc:postgresql://localhost:5454/Chatbot
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: localhost
      port: 6379
      password: redispass

cloudinary:
  cloud:
    name: dddwkgrcy
  api:
    key: 668583881613156
    secret: 7jymaVAgMxu5Pc50toz0YvwJ2ro

lingva-translate:
  base-url: http://localhost:3000/api/v1

faq:
  headers: 5
  subheaders: 3.4.4.1.4

email-address-of-the-admin-supervising-the:
  activity: admin1234@gmail.com
  contact-form: admin1234@gmail.com

packs:
  default-count: 3
  1:
    name: free
    advantages: Access to open data from the main portal. View public dashboards. Read open data. Limited search functions.
    currency-monthly-yearly-price: azn|0|0-usd|0|0-rub|0|0
  2:
    name: standard
    advantages: Download additional analytical capabilities and reports. Download documents in PDF and Excel format. Advanced search and filter functions. Receive email notifications.
    currency-monthly-yearly-price: azn|5|50-usd|3.5|35-rub|500|5000
  3:
    name: premium
    advantages: Additional analytical capabilities and report downloads. Download documents in PDF and Excel format. Advanced search and filter functions. Receive email notifications. Data upload and sharing. Access to exclusive dashboards. Fast support (priority support).
    currency-monthly-yearly-price: azn|10|100-usd|7|70-rub|1000|10000
